version: "3.1"

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=hubla
      - MYSQL_USER=hubla
      - MYSQL_PASSWORD=hubla
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE